version: '3.7'

services:
  foodscanningbackend:
    container_name: foodscanningbackend
    build:
      context: ./backend/
      dockerfile: docker/Dockerfile  
    restart: always
    volumes:
      - ./backend:/usr/src/app
    command: "npm run serve"
    ports:
      - 3000:3000
    depends_on: 
      - "foodscanningdb"
  foodscanningdb:
    container_name: foodscanningdb
    build:
      context: ./cassandra/
      dockerfile: ./Dockerfile
    environment: 
      - CASSANDRA_KEYSPACE=foodscanning
    ports:
      - 9042:9042
    volumes:
      - foodscanningdata:/var/lib/cassandra
    command: "sh /entrypoint-wrap.sh"
    restart: always
volumes:
  foodscanningdata:
    name: foodscanningdata